###################
## Model options
model_params:
  # layers: [64, 64, 64, 64, 64]
  # modes1: [10, 10, 10, 10]
  # modes2: [10, 10, 10, 10]
  # modes3: [10, 10, 10, 10]
  layers: [64, 64, 64, 64, 64]
  modes1: [8, 8, 8, 8]
  modes2: [8, 8, 8, 8]
  modes3: [8, 8, 8, 8]
  fc_dim: 128
  in_dim: 6 # 3 + in_fields
  out_dim: 3
  activation: 'gelu'
  pad_x: 5
  pad_y: 0
  pad_z: 0
  # input_norm: [1.0, 1.0, 1.0, 0.25, 0.25, 0.0001]
  # output_norm: [0.25, 0.25, 0.0001]
  input_norm: [1.0, 1.0, 1.0, 1.0, 1.0, 0.00025]
  output_norm: [1.0, 1.0, 0.00025]

###################
## Dataset options
dataset_params:
  # data_dir: 'mhd_data/simulation_outputs'
  data_dir: 'mhd_data/simulation_outputs_Re250'
  field_names: ['velocity', 'vector potential']
  output_names: 'output-???'
  dataset_type: 'mhd'
  name: 'MHDVecPot_Re250'
  num: 100
  num_train: 90
  num_test: 10
  # num_train: 100
  # num_test: 10
  sub_x: 1
  sub_t: 1
  ind_x: null
  ind_t: null
  nin: 3
  nout: 3
  fields: ['u', 'v', 'A']

###################
## Dataloader options
train_loader_params:
  batch_size: 1
  shuffle: True
  num_workers: 4
  pin_memory: True

val_loader_params:
  batch_size: 1
  shuffle: False
  num_workers: 4
  pin_memory: True

test_loader_params:
  batch_size: 1
  shuffle: False
  num_workers: 4
  pin_memory: True

###################
## Loss options
loss_params:
  nu: 0.004
  eta: 0.004
  rho0: 1.0
  
  data_weight: 5.0
  ic_weight: 1.0
  pde_weight: 1.0
  constraint_weight: 10.0
  
  use_data_loss: True
  use_ic_loss: True
  use_pde_loss: True
  use_constraint_loss: True
  
  u_weight: 1.0
  v_weight: 1.0
  A_weight: 1.0
  
  Du_weight: 1.0
  Dv_weight: 1.0
  DA_weight: 1_000_000
  
  div_B_weight: 1.0
  div_vel_weight: 1.0
  
  Lx: 1.0
  Ly: 1.0
  tend: 1.0

  use_weighted_mean: False
  
###################
## Optimizer options
optimizer_params:
  betas: [0.9, 0.999]
  lr: 0.001
  milestones: [25, 50, 75, 100, 125, 150]
  gamma: 0.5


###################
## Train params

train_params:
  epochs: 150
  ckpt_freq: 25
  ckpt_path: 'checkpoints/MHDVecPot/MHDVecPot_PINO_Re250.pt'
  load_ckpt: 'checkpoints/MHDVecPot/MHDVecPot_PINO_Re250.pt'

###################
## wandb params
wandb_params:
  wandb_dir: 'logs'
  wandb_project: 'MHD_PINO'
  wandb_group: 'MHDVecPot_Re250'
  wandb_num_plots: 1
  wandb_plot_freq: 5
  wandb_plot_types: ['ic', 'pred', 'true', 'error']

test:
  batchsize: 1
  ckpt: 'checkpoints/MHDVecPot/MHDVecPot_PINO_Re250.pt'
